/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_howfun_android_antguide_hf2djni_hf2d */

#ifndef _Included_com_howfun_android_antguide_hf2djni_hf2d
#define _Included_com_howfun_android_antguide_hf2djni_hf2d
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_howfun_android_antguide_hf2djni_hf2d
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_howfun_android_antguide_hf2djni_hf2d_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_howfun_android_antguide_hf2djni_hf2d
 * Method:    test
 * Signature: (Lcom/howfun/android/HF2D/AntSprite;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_howfun_android_antguide_hf2djni_hf2d_test
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
